---
name: unit_specs

'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest']
        ruby: ['3.0', '3.1']
    name: Unit test on ${{ matrix.os }} with Ruby ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake test 